# Generated by Django 5.0.1 on 2026-01-16 09:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_crb_score_customer_hybrid_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(choices=[('motor_vehicle', 'Motor Vehicle'), ('land_property', 'Land/Property'), ('business_asset', 'Business Asset'), ('chattels', 'Household/Office Chattels'), ('shares', 'Shares/Stocks'), ('fixed_deposit', 'Fixed Deposit'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pledged', 'Pledged'), ('discharged', 'Discharged'), ('auctioned', 'Auctioned')], default='available', max_length=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forced_sale_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valuation_date', models.DateField()),
                ('valuer_name', models.CharField(blank=True, max_length=100)),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='collateral_docs/')),
                ('description', models.TextField(blank=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('reg_number', models.CharField(blank=True, max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('logbook_number', models.CharField(blank=True, max_length=50)),
                ('lr_number', models.CharField(blank=True, max_length=100, verbose_name='LR/Parcel Number')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('property_size', models.CharField(blank=True, max_length=50)),
                ('tenure_type', models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Collateral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollateral',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('collateral_type', models.CharField(choices=[('motor_vehicle', 'Motor Vehicle'), ('land_property', 'Land/Property'), ('business_asset', 'Business Asset'), ('chattels', 'Household/Office Chattels'), ('shares', 'Shares/Stocks'), ('fixed_deposit', 'Fixed Deposit'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pledged', 'Pledged'), ('discharged', 'Discharged'), ('auctioned', 'Auctioned')], default='available', max_length=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forced_sale_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valuation_date', models.DateField()),
                ('valuer_name', models.CharField(blank=True, max_length=100)),
                ('document_upload', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('reg_number', models.CharField(blank=True, max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('logbook_number', models.CharField(blank=True, max_length=50)),
                ('lr_number', models.CharField(blank=True, max_length=100, verbose_name='LR/Parcel Number')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('property_size', models.CharField(blank=True, max_length=50)),
                ('tenure_type', models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical collateral',
                'verbose_name_plural': 'historical Collateral',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
