# Generated by Django 5.0.1 on 2026-01-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0002_emailconfiguration_valuer_valuationrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='valuer_name',
        ),
        migrations.RemoveField(
            model_name='historicalcollateral',
            name='valuer_name',
        ),
        migrations.AddField(
            model_name='collateral',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaterals', to='collateral.valuer'),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='valuer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.valuer'),
        ),
    ]
