# Generated by Django 5.0.1 on 2026-01-29 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collateral', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcollateral',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvaluationreport',
            name='collateral',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='historicalvaluationreport',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valuationreport',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_reports', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='valuationrequest',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_requests', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='valuationreport',
            name='valuation_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='collateral.valuationrequest'),
        ),
        migrations.AddField(
            model_name='historicalvaluationreport',
            name='valuation_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.valuationrequest'),
        ),
        migrations.AddField(
            model_name='valuationrequest',
            name='valuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='collateral.valuer'),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='valuer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.valuer'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaterals', to='collateral.valuer'),
        ),
    ]
