# Generated by Django 5.0.1 on 2026-02-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Date when current insurance cover expires', null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Date when current insurance cover expires', null=True),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
