# Generated by Django 5.0.1 on 2026-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_remove_collateral_valuer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='is_charged',
            field=models.BooleanField(default=False, help_text='Has the Security Deed been verified?'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='liquidation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='liquidation_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='is_charged',
            field=models.BooleanField(default=False, help_text='Has the Security Deed been verified?'),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='liquidation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='liquidation_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
