# Generated by Django 5.0.1 on 2026-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
