# Generated by Django 5.0.1 on 2026-01-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
    ]
