# Generated by Django 5.0.1 on 2026-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0004_collateral_insurance_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='tracker_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collateral',
            name='tracker_device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collateral',
            name='tracker_installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='tracker_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='tracker_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='tracker_device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='tracker_installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='tracker_installed',
            field=models.BooleanField(default=False),
        ),
    ]
