# Generated by Django 5.0.1 on 2026-02-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('collateral', '0005_collateral_tracker_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaterals', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicalcollateral',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
    ]
