openapi: 3.0.3
info:
  title: MFI & SACCO SaaS Platform API
  version: 1.0.0
  description: Core Financial Engine API Documentation
paths:
  /api/v1/auth/token/:
    post:
      operationId: v1_auth_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/v1/auth/token/refresh/:
    post:
      operationId: v1_auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/modules/:
    get:
      operationId: v1_modules_list
      description: Get list of all functional modules available on the platform.
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
          description: ''
  /api/v1/modules/{id}/:
    get:
      operationId: v1_modules_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this module.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
          description: ''
  /api/v1/subscriptions/:
    get:
      operationId: v1_subscriptions_list
      description: Get list of all active/expired subscriptions.
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
          description: ''
    post:
      operationId: v1_subscriptions_create
      description: Assign a new subscription plan to a tenant.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Subscription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Subscription'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
          description: ''
  /api/v1/subscriptions/{id}/:
    get:
      operationId: v1_subscriptions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this subscription.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
          description: ''
    put:
      operationId: v1_subscriptions_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this subscription.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Subscription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Subscription'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
          description: ''
    patch:
      operationId: v1_subscriptions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this subscription.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSubscription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSubscription'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSubscription'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
          description: ''
    delete:
      operationId: v1_subscriptions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this subscription.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/tenants/:
    get:
      operationId: v1_tenants_list
      description: Get a list of all tenants in the platform.
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'
          description: ''
    post:
      operationId: v1_tenants_create
      description: Provision a new tenant and its associated PostgreSQL schema.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tenant'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tenant'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: ''
  /api/v1/tenants/{id}/:
    get:
      operationId: v1_tenants_retrieve
      description: Get detailed profile of a specific tenant.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tenant.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: ''
    put:
      operationId: v1_tenants_update
      description: Update tenant profile details.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tenant.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tenant'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tenant'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: ''
    patch:
      operationId: v1_tenants_partial_update
      description: Partially update tenant profile details.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tenant.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTenant'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTenant'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTenant'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: ''
    delete:
      operationId: v1_tenants_destroy
      description: Decommission a tenant (DANGEROUS).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this tenant.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Domain:
      type: object
      properties:
        domain:
          type: string
          maxLength: 253
        is_primary:
          type: boolean
      required:
      - domain
    Module:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        description:
          type: string
      required:
      - id
      - name
    PatchedSubscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        tenant:
          type: integer
        plan:
          $ref: '#/components/schemas/PlanEnum'
        start_date:
          type: string
          format: date
          readOnly: true
        expiry_date:
          type: string
          format: date
        is_active:
          type: boolean
    PatchedTenant:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        schema_name:
          type: string
          maxLength: 63
        kra_pin:
          type: string
          nullable: true
          maxLength: 20
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_on:
          type: string
          format: date-time
          readOnly: true
        domains:
          type: array
          items:
            $ref: '#/components/schemas/Domain'
          readOnly: true
    PlanEnum:
      enum:
      - basic
      - premium
      - enterprise
      type: string
      description: |-
        * `basic` - Basic
        * `premium` - Premium
        * `enterprise` - Enterprise
    StatusEnum:
      enum:
      - active
      - suspended
      - pending
      type: string
      description: |-
        * `active` - Active
        * `suspended` - Suspended
        * `pending` - Pending
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        tenant:
          type: integer
        plan:
          $ref: '#/components/schemas/PlanEnum'
        start_date:
          type: string
          format: date
          readOnly: true
        expiry_date:
          type: string
          format: date
        is_active:
          type: boolean
      required:
      - expiry_date
      - id
      - start_date
      - tenant
    Tenant:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        schema_name:
          type: string
          maxLength: 63
        kra_pin:
          type: string
          nullable: true
          maxLength: 20
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_on:
          type: string
          format: date-time
          readOnly: true
        domains:
          type: array
          items:
            $ref: '#/components/schemas/Domain'
          readOnly: true
      required:
      - created_on
      - domains
      - id
      - name
      - schema_name
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
