# Generated by Django 5.0.1 on 2026-03-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staffallowance',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staffcontract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='staffdeduction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staffdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
    ]
