# Generated by Django 5.0.1 on 2026-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicalprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
