# Generated by Django 5.0.1 on 2026-01-16 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavingsaccount',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16),
        ),
    ]
