# Generated by Django 5.0.1 on 2026-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_class',
            field=models.CharField(choices=[('fixed', 'Fixed (e.g., Rent, Insurance)'), ('recurring', 'Recurring (e.g., Utilities, Subscriptions)'), ('variable', 'Variable (e.g., General Supplies)'), ('one_time', 'One-Time/Ad-hoc')], default='variable', help_text='Classification of the expense (e.g., fixed, recurring)', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='expense_class',
            field=models.CharField(choices=[('fixed', 'Fixed (e.g., Rent, Insurance)'), ('recurring', 'Recurring (e.g., Utilities, Subscriptions)'), ('variable', 'Variable (e.g., General Supplies)'), ('one_time', 'One-Time/Ad-hoc')], default='variable', help_text='Classification of the expense (e.g., fixed, recurring)', max_length=20),
        ),
    ]
