# Generated by Django 5.0.1 on 2026-02-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('treasury', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='coa_account',
            field=models.ForeignKey(blank=True, help_text='Link to the Chart of Accounts ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='historicalcashaccount',
            name='coa_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Link to the Chart of Accounts ledger', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccount'),
        ),
    ]
