# Generated by Django 5.0.1 on 2026-02-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_historicalorganization_primary_color_and_more'),
        ('treasury', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_transactions', to='accounts.organization'),
        ),
    ]
