# Generated by Django 5.0.1 on 2026-03-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_initial'),
        ('treasury', '0003_historicaltransaction_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='counterparty_coa',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The opposite side of the transaction for manual records', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty_coa',
            field=models.ForeignKey(blank=True, help_text='The opposite side of the transaction for manual records', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='accounting.chartofaccount'),
        ),
    ]
