# Generated by Django 5.0.1 on 2026-01-16 11:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0002_emailconfiguration_valuer_valuationrequest_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='collateral',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loan-to-Value ratio at disbursement (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='max_ltv_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Maximum Loan-to-Value ratio allowed (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='loan',
            name='ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loan-to-Value ratio at disbursement (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_ltv_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Maximum Loan-to-Value ratio allowed (%)', max_digits=5),
        ),
    ]
