# Generated by Django 5.0.1 on 2026-02-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_initial'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloandeduction',
            name='coa_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='coa_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
    ]
