# Generated by Django 5.0.1 on 2026-01-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepaymentschedule',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_schedules', to='loans.loanapplication'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='loans.loan'),
        ),
    ]
