# Generated by Django 5.0.1 on 2026-02-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='is_refinanced',
            field=models.BooleanField(default=False, help_text='True if this loan was paid off via refinancing'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='refinanced_at',
            field=models.DateTimeField(blank=True, help_text='When this loan was refinanced', null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='refinanced_by_loan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The new loan that paid off this one', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='net_disbursement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount disbursed to customer (principal - payoff)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='payoff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount allocated to pay off the existing loan', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='refinances_loan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The loan this application will pay off', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_refinanced',
            field=models.BooleanField(default=False, help_text='True if this loan was paid off via refinancing'),
        ),
        migrations.AddField(
            model_name='loan',
            name='refinanced_at',
            field=models.DateTimeField(blank=True, help_text='When this loan was refinanced', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='refinanced_by_loan',
            field=models.ForeignKey(blank=True, help_text='The new loan that paid off this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinanced_loans', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='net_disbursement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount disbursed to customer (principal - payoff)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='payoff_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount allocated to pay off the existing loan', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='refinances_loan',
            field=models.ForeignKey(blank=True, help_text='The loan this application will pay off', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanced_by_applications', to='loans.loan'),
        ),
    ]
