# Generated by Django 5.0.1 on 2026-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_historicalloan_is_refinanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanapplication',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text='Validity of the offer letter', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text='Validity of the offer letter', null=True),
        ),
    ]
