# Generated by Django 5.0.1 on 2026-01-16 13:13

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_historicalloanapplication_requested_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repaymentschedule',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='historicalloanrepayment',
            old_name='fees_paid',
            new_name='fee_paid',
        ),
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='fees_paid',
            new_name='fee_paid',
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalloanrepayment',
            name='schedule_entry',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='schedule_entry',
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='arrears_category',
            field=models.CharField(choices=[('current', 'Current'), ('1-30', '1-30 Days'), ('31-60', '31-60 Days'), ('61-90', '61-90 Days'), ('90+', '90+ Days')], default='current', help_text='Arrears aging bucket', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='days_in_arrears',
            field=models.IntegerField(default=0, help_text='Current days overdue'),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='default_term',
            field=models.PositiveIntegerField(default=12, help_text='Default loan period'),
        ),
        migrations.AddField(
            model_name='loan',
            name='arrears_category',
            field=models.CharField(choices=[('current', 'Current'), ('1-30', '1-30 Days'), ('31-60', '31-60 Days'), ('61-90', '61-90 Days'), ('90+', '90+ Days')], default='current', help_text='Arrears aging bucket', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='days_in_arrears',
            field=models.IntegerField(default=0, help_text='Current days overdue'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_term',
            field=models.PositiveIntegerField(default=12, help_text='Default loan period'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='calculated_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose of the loan'),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='requested_term',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalloanfee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Grace period before penalties'),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='interest_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='max_ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Loan-to-Value ratio (%) if collateral required', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='max_term',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='min_term',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalloanproduct',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily penalty rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalloanrepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalloanrepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='calculated_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose of the loan'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='requested_term',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Grace period before penalties'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_ltv_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Loan-to-Value ratio (%) if collateral required', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_term',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='min_term',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily penalty rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='interest_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='principal_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='CollectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Legal'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low (1-30 days)'), ('medium', 'Medium (31-60 days)'), ('high', 'High (61-90 days)'), ('critical', 'Critical (90+ days)')], default='low', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_case', to='loans.loan')),
            ],
            options={
                'verbose_name_plural': 'Collection Cases',
                'ordering': ['-priority', '-days_overdue'],
            },
        ),
        migrations.CreateModel(
            name='CollectionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'Physical Visit'), ('letter', 'Letter'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(help_text='Details of the collection activity')),
                ('customer_response', models.TextField(blank=True, help_text="Customer's response or commitment")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='loans.collectioncase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollectionCase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Legal'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low (1-30 days)'), ('medium', 'Medium (31-60 days)'), ('high', 'High (61-90 days)'), ('critical', 'Critical (90+ days)')], default='low', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opened_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
            ],
            options={
                'verbose_name': 'historical collection case',
                'verbose_name_plural': 'historical Collection Cases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCollectionNote',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'Physical Visit'), ('letter', 'Letter'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(help_text='Details of the collection activity')),
                ('customer_response', models.TextField(blank=True, help_text="Customer's response or commitment")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.collectioncase')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical collection note',
                'verbose_name_plural': 'historical collection notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPromiseToPay',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promised_date', models.DateField()),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('broken', 'Broken')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.collectioncase')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical promise to pay',
                'verbose_name_plural': 'historical Promises to Pay',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecoveryAction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('action_type', models.CharField(choices=[('demand_letter', 'Demand Letter Sent'), ('legal_notice', 'Legal Notice'), ('court_filing', 'Court Filing'), ('collateral_seizure', 'Collateral Seizure'), ('auction', 'Auction Scheduled'), ('settlement', 'Settlement Agreement'), ('write_off', 'Write-off Approved')], max_length=30)),
                ('action_date', models.DateField()),
                ('details', models.TextField(help_text='Details of the recovery action taken')),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('document', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
            ],
            options={
                'verbose_name': 'historical recovery action',
                'verbose_name_plural': 'historical recovery actions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRepaymentSchedule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fees_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
            ],
            options={
                'verbose_name': 'historical repayment schedule',
                'verbose_name_plural': 'historical repayment schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promised_date', models.DateField()),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('broken', 'Broken')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='loans.collectioncase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Promises to Pay',
                'ordering': ['-promised_date'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('demand_letter', 'Demand Letter Sent'), ('legal_notice', 'Legal Notice'), ('court_filing', 'Court Filing'), ('collateral_seizure', 'Collateral Seizure'), ('auction', 'Auction Scheduled'), ('settlement', 'Settlement Agreement'), ('write_off', 'Write-off Approved')], max_length=30)),
                ('action_date', models.DateField()),
                ('details', models.TextField(help_text='Details of the recovery action taken')),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('document', models.FileField(blank=True, null=True, upload_to='recovery_docs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='loans.loan')),
            ],
            options={
                'ordering': ['-action_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='repaymentschedule',
            name='paid_date',
        ),
    ]
