# Generated by Django 5.0.1 on 2026-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_historicalrepaymentschedule_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanproduct',
            name='interest_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='flat', help_text='Calculation method for interest', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='interest_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance')], default='flat', help_text='Calculation method for interest', max_length=20),
        ),
    ]
