# Generated by Django 5.0.1 on 2026-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0004_collateral_color_historicalcollateral_color'),
        ('loans', '0004_historicalloandocument_loandocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='collaterals',
            field=models.ManyToManyField(blank=True, help_text='Assets pledged as security for this application', related_name='loan_applications_m2m', to='collateral.collateral'),
        ),
    ]
