# Generated by Django 5.0.1 on 2026-01-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_historicalloanproduct_interest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanapplication',
            name='signed_disbursement_letter',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='signed_disbursement_letter',
            field=models.FileField(blank=True, null=True, upload_to='signed_disbursements/'),
        ),
    ]
