# Generated by Django 5.0.1 on 2026-01-28 08:27

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_options_alter_loanapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanapplication',
            name='discharge_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='valuation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='discharge_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='valuation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalloanfee',
            name='fee_type',
            field=models.CharField(choices=[('processing', 'Processing Fee'), ('insurance', 'Insurance'), ('legal', 'Legal Fee'), ('collateral_discharge', 'Collateral Discharge Fee'), ('valuation', 'Valuation Fee'), ('late_penalty', 'Late Penalty'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanfee',
            name='fee_type',
            field=models.CharField(choices=[('processing', 'Processing Fee'), ('insurance', 'Insurance'), ('legal', 'Legal Fee'), ('collateral_discharge', 'Collateral Discharge Fee'), ('valuation', 'Valuation Fee'), ('late_penalty', 'Late Penalty'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='CollateralDischarge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('letter_sent', 'Discharge Letter Sent'), ('customer_confirmed', 'Customer Confirmed Collection'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('discharge_letter', models.FileField(blank=True, null=True, upload_to='discharge_letters/')),
                ('collection_confirmation', models.FileField(blank=True, null=True, upload_to='collection_confirmations/')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_process', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCollateralDischarge',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('letter_sent', 'Discharge Letter Sent'), ('customer_confirmed', 'Customer Confirmed Collection'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('discharge_letter', models.TextField(blank=True, max_length=100, null=True)),
                ('collection_confirmation', models.TextField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
            ],
            options={
                'verbose_name': 'historical collateral discharge',
                'verbose_name_plural': 'historical collateral discharges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
