# Generated by Django 5.0.1 on 2026-02-06 06:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_historicalloanapplication_offer_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='approved_repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', help_text='Frequency of repayment installments', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', help_text='How late payment penalties are calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty amount or percentage', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', help_text='Default frequency of repayment installments', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', help_text='Frequency of repayment installments', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_grace_period',
            field=models.PositiveIntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', help_text='How late payment penalties are calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty amount or percentage', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually'), ('bullet', 'Bullet (One-off at end)')], default='monthly', help_text='Default frequency of repayment installments', max_length=20),
        ),
    ]
