# Generated by Django 5.0.1 on 2026-01-28 10:01

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_historicalloanapplication_discharge_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='grace_period_days',
        ),
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='processing_fee_type',
        ),
        migrations.RemoveField(
            model_name='historicalloanproduct',
            name='processing_fee_value',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='grace_period_days',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='processing_fee_type',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='processing_fee_value',
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='approved_interest_method',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance'), ('interest_only', 'Interest Only')], help_text='Method used to calculate interest', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='approved_interest_period',
            field=models.CharField(blank=True, choices=[('per_month', 'Per Month'), ('per_day', 'Per Day'), ('per_year', 'Per Annum')], help_text='Period for interest calculation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='approved_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate (%) approved for this specific loan', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='credit_score_at_application',
            field=models.IntegerField(blank=True, help_text="Customer's credit score at time of application", null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='legal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='other_fees',
            field=models.JSONField(blank=True, default=dict, help_text='Additional flexible fees'),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='processing_fee_basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', help_text='How processing fee is calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='processing_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Processing fee percentage if basis is 'percentage'", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='min_collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum collateral value required if collateral is mandatory', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='min_credit_score',
            field=models.IntegerField(blank=True, help_text='Minimum credit score required for this product', null=True),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='suggested_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested annual interest rate (%) - can be overridden per loan', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='suggested_processing_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested processing fee percentage - can be overridden per loan', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_interest_method',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance'), ('interest_only', 'Interest Only')], help_text='Method used to calculate interest', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_interest_period',
            field=models.CharField(blank=True, choices=[('per_month', 'Per Month'), ('per_day', 'Per Day'), ('per_year', 'Per Annum')], help_text='Period for interest calculation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate (%) approved for this specific loan', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score_at_application',
            field=models.IntegerField(blank=True, help_text="Customer's credit score at time of application", null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='legal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='other_fees',
            field=models.JSONField(blank=True, default=dict, help_text='Additional flexible fees'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='processing_fee_basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', help_text='How processing fee is calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='processing_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Processing fee percentage if basis is 'percentage'", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_collateral_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum collateral value required if collateral is mandatory', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_credit_score',
            field=models.IntegerField(blank=True, help_text='Minimum credit score required for this product', null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='suggested_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested annual interest rate (%) - can be overridden per loan', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='suggested_processing_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested processing fee percentage - can be overridden per loan', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalCreditScoringRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('min_credit_score', models.IntegerField(help_text='Minimum score (inclusive)')),
                ('max_credit_score', models.IntegerField(help_text='Maximum score (inclusive)')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, help_text='Minimum allowed interest rate (%)', max_digits=5)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, help_text='Maximum allowed interest rate (%)', max_digits=5)),
                ('suggested_interest_rate', models.DecimalField(decimal_places=2, help_text='Suggested/default interest rate (%)', max_digits=5)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Processing fee percentage for this risk category', max_digits=5)),
                ('risk_category', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='Product-specific rule. If null, applies to all products', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loanproduct')),
            ],
            options={
                'verbose_name': 'historical credit scoring rule',
                'verbose_name_plural': 'historical credit scoring rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CreditScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_credit_score', models.IntegerField(help_text='Minimum score (inclusive)')),
                ('max_credit_score', models.IntegerField(help_text='Maximum score (inclusive)')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, help_text='Minimum allowed interest rate (%)', max_digits=5)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, help_text='Maximum allowed interest rate (%)', max_digits=5)),
                ('suggested_interest_rate', models.DecimalField(decimal_places=2, help_text='Suggested/default interest rate (%)', max_digits=5)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Processing fee percentage for this risk category', max_digits=5)),
                ('risk_category', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product-specific rule. If null, applies to all products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-min_credit_score'],
                'unique_together': {('product', 'min_credit_score', 'max_credit_score')},
            },
        ),
    ]
