# Generated by Django 5.0.1 on 2026-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_historicalloanapplication_signed_disbursement_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='repayment_channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash/In-Person')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='repayment_channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash/In-Person')], default='mpesa', help_text='Primary channel for loan repayments', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash/In-Person')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash/In-Person')], default='mpesa', help_text='Primary channel for loan repayments', max_length=20),
        ),
    ]
