# Generated by Django 5.0.1 on 2026-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0004_collateral_color_historicalcollateral_color'),
        ('loans', '0005_loanapplication_collaterals'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='collaterals',
            field=models.ManyToManyField(blank=True, help_text='Assets pledged as security for this loan', related_name='loans_m2m', to='collateral.collateral'),
        ),
    ]
