# Generated by Django 5.0.1 on 2026-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_historicalloan_repayment_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='disbursement_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='mpesa', max_length=20),
        ),
    ]
