# Generated by Django 5.0.1 on 2026-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_collaterals'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanproduct',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', help_text='How often the penalty is applied (per day, per week, per month, or once per missed installment)', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_basis',
            field=models.CharField(choices=[('per_day', 'Per Day (daily accrual)'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('per_installment', 'Per Installment (one-off flat fee)')], default='per_day', help_text='How often the penalty is applied (per day, per week, per month, or once per missed installment)', max_length=20),
        ),
    ]
