# Generated by Django 5.0.1 on 2026-01-28 11:40

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_historicalloanproduct_grace_period_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanapplication',
            name='disbursement_letter_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='offer_letter_file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='signed_offer_letter',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='disbursement_letters/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='loan_offers/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='signed_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='signed_offers/'),
        ),
        migrations.AlterField(
            model_name='historicalloanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved (Pending Offer)'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved (Pending Offer)'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalLoanDeduction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='e.g. Processing Fee, Insurance, Legal Fee', max_length=100)),
                ('charge_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_withheld', models.BooleanField(default=True, help_text='If true, this amount is deducted from the principal during disbursement')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loanapplication')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical loan deduction',
                'verbose_name_plural': 'historical loan deductions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Processing Fee, Insurance, Legal Fee', max_length=100)),
                ('charge_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Principal')], default='fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_withheld', models.BooleanField(default=True, help_text='If true, this amount is deducted from the principal during disbursement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='loans.loanapplication')),
            ],
        ),
    ]
