# Generated by Django 5.0.1 on 2026-02-06 08:08

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_historicalloancomment_loancomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMpesaC2BTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('trans_id', models.CharField(db_index=True, help_text='M-Pesa receipt number', max_length=50)),
                ('trans_time', models.DateTimeField()),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_short_code', models.CharField(max_length=20)),
                ('bill_ref_number', models.CharField(help_text='Loan number or account reference', max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50)),
                ('msisdn', models.CharField(help_text='Customer phone number', max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('confirmed', 'Confirmed & Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('raw_data', models.JSONField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
                ('repayment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loanrepayment')),
            ],
            options={
                'verbose_name': 'historical M-Pesa C2B Transaction',
                'verbose_name_plural': 'historical M-Pesa C2B Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MpesaC2BTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_id', models.CharField(help_text='M-Pesa receipt number', max_length=50, unique=True)),
                ('trans_time', models.DateTimeField()),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_short_code', models.CharField(max_length=20)),
                ('bill_ref_number', models.CharField(help_text='Loan number or account reference', max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50)),
                ('msisdn', models.CharField(help_text='Customer phone number', max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('confirmed', 'Confirmed & Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('raw_data', models.JSONField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_c2b_transactions', to='loans.loan')),
                ('repayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_c2b_transaction', to='loans.loanrepayment')),
            ],
            options={
                'verbose_name': 'M-Pesa C2B Transaction',
                'verbose_name_plural': 'M-Pesa C2B Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
