# Generated by Django 5.0.1 on 2026-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_historicalloan_disbursement_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='disbursement_details',
            field=models.JSONField(blank=True, default=dict, help_text='Payment details used for disbursement (verified at time of payment)'),
        ),
        migrations.AddField(
            model_name='historicalloanapplication',
            name='disbursement_details',
            field=models.JSONField(blank=True, default=dict, help_text='Payment details used for disbursement (e.g. M-Pesa number, Bank account)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_details',
            field=models.JSONField(blank=True, default=dict, help_text='Payment details used for disbursement (verified at time of payment)'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_details',
            field=models.JSONField(blank=True, default=dict, help_text='Payment details used for disbursement (e.g. M-Pesa number, Bank account)'),
        ),
    ]
