# Generated by Django 5.0.1 on 2026-03-14 04:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_add_penalty_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepaymentschedule',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest collected against this installment so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalrepaymentschedule',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty collected against this installment so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalrepaymentschedule',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal collected against this installment so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest collected against this installment so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty collected against this installment so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal collected against this installment so far', max_digits=12),
        ),
    ]
