# Generated by Django 5.0.1 on 2026-01-28 12:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0004_collateral_is_charged_collateral_liquidation_date_and_more'),
        ('customers', '0006_customer_verification_notes_and_more'),
        ('loans', '0007_historicalloanapplication_disbursement_letter_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoanGuarantor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, help_text='e.g. Spouse, Employer, Friend', max_length=50)),
                ('amount_guaranteed', models.DecimalField(decimal_places=2, help_text='Amount this person is guaranteeing', max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('signed_guaranty_form', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loanapplication')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pledged_collateral', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collateral.collateral')),
            ],
            options={
                'verbose_name': 'historical loan guarantor',
                'verbose_name_plural': 'historical loan guarantors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, help_text='e.g. Spouse, Employer, Friend', max_length=50)),
                ('amount_guaranteed', models.DecimalField(decimal_places=2, help_text='Amount this person is guaranteeing', max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('signed_guaranty_form', models.FileField(blank=True, null=True, upload_to='guaranty_forms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanapplication')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantorships', to='customers.customer')),
                ('pledged_collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_pledges', to='collateral.collateral')),
            ],
        ),
    ]
