# Generated by Django 5.0.1 on 2026-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_historicalloanguarantor_loanguarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanproduct',
            name='suggested_interest_period',
            field=models.CharField(choices=[('per_month', 'Per Month'), ('per_day', 'Per Day'), ('per_year', 'Per Annum')], default='per_year', help_text='Default interest calculation period', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='suggested_interest_period',
            field=models.CharField(choices=[('per_month', 'Per Month'), ('per_day', 'Per Day'), ('per_year', 'Per Annum')], default='per_year', help_text='Default interest calculation period', max_length=20),
        ),
    ]
