# Generated by Django 5.0.1 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_historicalloan_disbursement_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='disbursement_proof',
            field=models.TextField(blank=True, help_text='Upload receipt/screenshot for manual disbursement verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the disbursement process', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_proof',
            field=models.FileField(blank=True, help_text='Upload receipt/screenshot for manual disbursement verification', null=True, upload_to='disbursements/proof/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the disbursement process', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='disbursement_reference',
            field=models.CharField(blank=True, help_text='API transaction ID or manual reference code', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_reference',
            field=models.CharField(blank=True, help_text='API transaction ID or manual reference code', max_length=100),
        ),
    ]
