# Generated by Django 5.0.1 on 2026-03-14 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_per_installment_payment_buckets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='is_restructured',
            field=models.BooleanField(default=False, help_text='True if this loan has been restructured in-place'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='original_term',
            field=models.PositiveIntegerField(blank=True, help_text='The original term of the loan before restructuring', null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='restructure_notes',
            field=models.TextField(blank=True, help_text='Notes/reason for restructuring'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='restructured_at',
            field=models.DateTimeField(blank=True, help_text='When this loan was last restructured', null=True),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='restructured_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Staff member who performed the restructuring', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_restructured',
            field=models.BooleanField(default=False, help_text='True if this loan has been restructured in-place'),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_term',
            field=models.PositiveIntegerField(blank=True, help_text='The original term of the loan before restructuring', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructure_notes',
            field=models.TextField(blank=True, help_text='Notes/reason for restructuring'),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructured_at',
            field=models.DateTimeField(blank=True, help_text='When this loan was last restructured', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructured_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the restructuring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructured_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
