# Generated by Django 5.0.1 on 2026-03-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_add_loan_restructuring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepaymentschedule',
            name='last_penalty_accrual_date',
            field=models.DateField(blank=True, help_text='Last date a penalty unit was applied to this schedule', null=True),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='last_penalty_accrual_date',
            field=models.DateField(blank=True, help_text='Last date a penalty unit was applied to this schedule', null=True),
        ),
    ]
