# Generated by Django 5.0.1 on 2026-03-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_historicalrepaymentschedule_last_penalty_accrual_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloanrepayment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalloanrepayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalloanrepayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_repayments', to=settings.AUTH_USER_MODEL),
        ),
    ]
