# Generated by Django 5.0.1 on 2026-01-29 08:49

import simple_history.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvestment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('investment_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, help_text='Annual return rate %', max_digits=5)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('term_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('total_expected_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical investment',
                'verbose_name_plural': 'historical investments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvestor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('investor_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('investor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('institution', 'Institution')], default='individual', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID or Company Reg', max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical investor',
                'verbose_name_plural': 'historical investors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvestorPayout',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('payout_type', models.CharField(choices=[('interest', 'Interest Payment'), ('principal', 'Principal Return'), ('bonus', 'Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(default='bank_transfer', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical investor payout',
                'verbose_name_plural': 'historical investor payouts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, help_text='Annual return rate %', max_digits=5)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('term_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('total_expected_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('investor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('institution', 'Institution')], default='individual', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID or Company Reg', max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('interest', 'Interest Payment'), ('principal', 'Principal Return'), ('bonus', 'Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(default='bank_transfer', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payout_date'],
            },
        ),
    ]
