# Generated by Django 5.0.1 on 2026-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='primary_color',
            field=models.CharField(blank=True, default='#2EAD8F', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, default='#2EAD8F', help_text='Primary brand color (hex code)', max_length=7),
        ),
    ]
