# Generated by Django 5.0.1 on 2026-01-29 08:49

import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('borrower_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('institution', 'Institution'), ('group', 'Group')], default='individual', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, help_text='For companies and institutions', max_length=150, null=True)),
                ('contact_person_name', models.CharField(blank=True, help_text='Primary contact person for the entity', max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('alien_id', 'Alien ID'), ('registration_cert', 'Registration Certificate'), ('incorporation_cert', 'Certificate of Incorporation')], default='national_id', max_length=20)),
                ('id_number', models.CharField(help_text='National ID or Registration Number', max_length=50, unique=True)),
                ('tax_id', models.CharField(blank=True, help_text='KRA PIN or Tax ID', max_length=50, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='borrower_ids/')),
                ('date_of_birth', models.DateField(blank=True, help_text='DOB for individuals', null=True)),
                ('incorporation_date', models.DateField(blank=True, help_text='Date of registration/incorporation for entities', null=True)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student'), ('business_owner', 'Business Owner'), ('operational', 'Operational')], default='employed', max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly Income or Revenue', max_digits=12)),
                ('crb_score', models.IntegerField(blank=True, null=True)),
                ('internal_score', models.IntegerField(default=0)),
                ('hybrid_score', models.IntegerField(blank=True, null=True)),
                ('last_crb_check', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When borrower was assigned to current officer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRBReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CRB Report',
                'verbose_name_plural': 'CRB Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBorrower',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('borrower_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('borrower_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('institution', 'Institution'), ('group', 'Group')], default='individual', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, help_text='For companies and institutions', max_length=150, null=True)),
                ('contact_person_name', models.CharField(blank=True, help_text='Primary contact person for the entity', max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('alien_id', 'Alien ID'), ('registration_cert', 'Registration Certificate'), ('incorporation_cert', 'Certificate of Incorporation')], default='national_id', max_length=20)),
                ('id_number', models.CharField(db_index=True, help_text='National ID or Registration Number', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='KRA PIN or Tax ID', max_length=50, null=True)),
                ('id_document', models.TextField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='DOB for individuals', null=True)),
                ('incorporation_date', models.DateField(blank=True, help_text='Date of registration/incorporation for entities', null=True)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student'), ('business_owner', 'Business Owner'), ('operational', 'Operational')], default='employed', max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly Income or Revenue', max_digits=12)),
                ('crb_score', models.IntegerField(blank=True, null=True)),
                ('internal_score', models.IntegerField(default=0)),
                ('hybrid_score', models.IntegerField(blank=True, null=True)),
                ('last_crb_check', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When borrower was assigned to current officer', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical borrower',
                'verbose_name_plural': 'historical borrowers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
