# Generated by Django 5.0.1 on 2026-01-16 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='crb_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='hybrid_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_crb_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='crb_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='hybrid_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='internal_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='last_crb_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CRBReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crb_reports', to='customers.customer')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_crb_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRB Report',
                'verbose_name_plural': 'CRB Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
