# Generated by Django 5.0.1 on 2026-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_crb_score_customer_hybrid_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
