# Generated by Django 5.0.1 on 2026-02-17 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_historicalorganization_primary_color_and_more'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowercontact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_contacts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='crbreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crb_reports', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicalborrowercontact',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization'),
        ),
    ]
