# Generated by Django 5.0.1 on 2026-01-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_customer_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When customer was assigned to current officer', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_officer',
            field=models.ForeignKey(blank=True, help_text="Loan officer responsible for this customer's portfolio", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When customer was assigned to current officer', null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='loan_officer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Loan officer responsible for this customer's portfolio", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
