# Generated by Django 5.0.1 on 2026-02-18 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_borrowercontact_organization_crbreport_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, help_text='e.g. Personal, Work, M-Pesa', max_length=50)),
                ('is_mpesa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='customers.borrower')),
            ],
        ),
    ]
