# Generated by Django 5.0.1 on 2026-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', max_length=20),
        ),
    ]
