# Generated by Django 5.0.1 on 2026-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_security_credential',
            field=models.TextField(blank=True, help_text='Encrypted security credential for B2C/disbursements'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_security_credential',
            field=models.TextField(blank=True, help_text='Encrypted security credential for B2C/disbursements'),
        ),
    ]
