# Generated by Django 5.0.1 on 2026-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('disbursement_letter', 'Disbursement Checklist'), ('other', 'Other')], default='offer_letter', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttemplate',
            name='template_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('disbursement_letter', 'Disbursement Checklist'), ('other', 'Other')], default='offer_letter', max_length=50),
        ),
    ]
