# Generated by Django 5.0.1 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_documenttemplate_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='bank_api_account_number',
            field=models.CharField(blank=True, help_text='Source account for transfers', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='bank_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable automated bank transfers'),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='bank_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='bank_api_provider',
            field=models.CharField(blank=True, help_text='e.g., pesalink, ipay, jenga_api', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='bank_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_api_account_number',
            field=models.CharField(blank=True, help_text='Source account for transfers', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_api_enabled',
            field=models.BooleanField(default=False, help_text='Enable automated bank transfers'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_api_provider',
            field=models.CharField(blank=True, help_text='e.g., pesalink, ipay, jenga_api', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='bank_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
