# Generated by Django 5.0.1 on 2026-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_historicaltenantsettings_mpesa_security_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('disbursement_letter', 'Disbursement Letter'), ('loan_statement', 'Loan Statement'), ('other', 'Other')], default='offer_letter', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttemplate',
            name='template_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('disbursement_letter', 'Disbursement Letter'), ('loan_statement', 'Loan Statement'), ('other', 'Other')], default='offer_letter', max_length=50),
        ),
    ]
