# Generated by Django 5.0.1 on 2026-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_historicaltenantsettings_tenantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_environment',
            field=models.CharField(default='sandbox', help_text='sandbox or production', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_initiator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_initiator_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='overdue_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Days before due date to send reminder'),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='sms_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='sms_provider',
            field=models.CharField(blank=True, help_text='africas_talking, infobip, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_environment',
            field=models.CharField(default='sandbox', help_text='sandbox or production', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_initiator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_initiator_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='overdue_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='reminder_days_before',
            field=models.IntegerField(default=3, help_text='Days before due date to send reminder'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='sms_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='sms_provider',
            field=models.CharField(blank=True, help_text='africas_talking, infobip, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
