# Generated by Django 5.0.1 on 2026-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_historicaltenantsettings_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_city',
            field=models.CharField(blank=True, default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Official registered company name', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_postal_address',
            field=models.CharField(blank=True, help_text='P.O. Box address', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='company_tagline',
            field=models.CharField(blank=True, help_text='Slogan or motto for reports', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E3A8A', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='report_footer_text',
            field=models.TextField(blank=True, help_text='Standard footer text for all reports'),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Secondary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='tax_identification',
            field=models.CharField(blank=True, help_text='TIN/VAT number', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_city',
            field=models.CharField(blank=True, default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Official registered company name', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_postal_address',
            field=models.CharField(blank=True, help_text='P.O. Box address', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='company_tagline',
            field=models.CharField(blank=True, help_text='Slogan or motto for reports', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E3A8A', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='report_footer_text',
            field=models.TextField(blank=True, help_text='Standard footer text for all reports'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Secondary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tax_identification',
            field=models.CharField(blank=True, help_text='TIN/VAT number', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaltenantsettings',
            name='company_address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='historicaltenantsettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='company_address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='tenant_logos/'),
        ),
    ]
