# Generated by Django 5.0.1 on 2026-01-27 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_historicaltenantsettings_company_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltenantsettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='historicaltenantsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='historicaltenantsettings',
            name='report_footer_text',
        ),
        migrations.RemoveField(
            model_name='historicaltenantsettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='report_footer_text',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='crb_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='crb_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='crb_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='crb_provider',
            field=models.CharField(blank=True, default='metropol', help_text='metropol, transunion', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='identity_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='identity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='identity_provider',
            field=models.CharField(blank=True, default='smile_identity', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='crb_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='crb_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='crb_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='crb_provider',
            field=models.CharField(blank=True, default='metropol', help_text='metropol, transunion', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='identity_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='identity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='identity_provider',
            field=models.CharField(blank=True, default='smile_identity', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='history_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
