# Generated by Django 5.0.1 on 2026-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_historicaltenantsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='logo',
            field=models.TextField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E3A8A', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='report_footer_text',
            field=models.TextField(blank=True, help_text='Standard footer text for all reports'),
        ),
        migrations.AddField(
            model_name='historicaltenantsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Secondary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (PNG/JPG, max 2MB)', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E3A8A', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='report_footer_text',
            field=models.TextField(blank=True, help_text='Standard footer text for all reports'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Secondary brand color (hex code)', max_length=7),
        ),
    ]
